const { DynamicTool } = require("@langchain/core/tools");
const { ChatOpenAI } = require("@langchain/openai");
const { AgentExecutor, createReactAgent } = require("langchain/agents");
const { PromptTemplate } = require("@langchain/core/prompts");

const readCSV = require("../services/csvServices");
const { calculateEscalationLevel, getFollowUpStage } = require("../services/escalationEngine");
const generateEmail = require("../services/aiServices");
const saveLog = require("../services/logService");

const readInvoicesTool = new DynamicTool({
    name: "read_invoices",
    description: "Reads all invoices from the CSV file. Call this first. Returns array of invoice objects.",
    func: async () => {
        const invoices = await readCSV();
        return JSON.stringify(invoices);
    }
});

const calculateStageTool = new DynamicTool({
    name: "calculate_stage",
    description: "Takes a JSON array of invoices and calculates days overdue and stage for each one. Returns enriched invoices.",
    
    func: async (invoicesJson) => {
        const invoices = JSON.parse(invoicesJson);

        const enriched = invoices.map((invoice) => {
            const daysOverdue = calculateEscalationLevel(invoice.dueDate);

            const followUp = getFollowUpStage(daysOverdue);

            return {
                ...invoice,
                daysOverdue,
                stage: followUp.stage,
                tone: followUp.tone
            };
        });

        return JSON.stringify(enriched);
    }
});

const generateEmailTool = new DynamicTool({
    name: "generate_email",
    description: "Takes enriched invoice JSON array and generates personalised emails for each invoice. Skips invoices with 0 or negative days overdue and ESCALATED invoices.",
    func: async (enrichedJson) => {
        const enriched = JSON.parse(enrichedJson);
        const result = [];
        for (const invoice of enriched) {
            if (invoice.daysOverdue <= 0) {
                result.push({
                    invoiceNumber: invoice.invoiceNumber,
                    skipped: true,
                    reason: "Not overdue"
                });
                continue;
            }
            if (invoice.stage === "ESCALATED") {
                result.push({
                    invoiceNumber: invoice.invoiceNumber,
                    skipped: true,
                    reason: "Flagged for legal review"
                });
                continue;
            }
            const generatedEmail = await generateEmail(invoice);
            result.push({
                ...invoice,
                generatedEmail,
                skipped: false
            });
        }
        return JSON.stringify(result);
    }
});

const saveLogsTool = new DynamicTool({
    name: "save_logs",
    description: "Takes the results array and saves each generated email to the audit log. Skips invoices marked as skipped.",

    func: async (resultsJson) => {
        console.log("=== SAVE LOGS TOOL CALLED ===");
        console.log("Raw input:", resultsJson);
        const results = JSON.parse(resultsJson);
        console.log("First result:", JSON.stringify(results[0], null, 2));

        let saved = 0;
        for (const result of results) {
            if (result.skipped) continue;
            await saveLog({
                invoiceNumber: result.invoiceNumber,
                clientName: result.clientName,
                stage: result.stage,
                tone: result.tone || "N/A",
                generatedEmail: result.generatedEmail
                    ? {
                        subject: result.generatedEmail.subject,
                        body: result.generatedEmail.body
                    }
                    : {
                        subject: "Generated by Agent",
                        body: result.emailBody || "No body"
                    },
                timestamp: new Date().toISOString(),
                status: "AGENT-GENERATED"
            });
            saved++;
        }
        return `Successfully saved ${saved} email logs.`;
    }
});

// const runInvoiceAgent = async () => {
//     const llm = new ChatOpenAI({
//         configuration: {
//             baseURL: "https://openrouter.ai/api/v1",
//         },
//         openAIApiKey: process.env.OPENROUTER_API_KEY,
//         modelName: "openrouter/auto",
//         temperature: 0
//     });

//     const tools = [
//         readInvoicesTool,
//         calculateStageTool,
//         generateEmailTool,
//         saveLogsTool
//     ];

//     const prompt = PromptTemplate.fromTemplate(`
// Answer the following questions as best you can.

// You have access to the following tools:

// {tools}

// Use the following format:

// Question: the input question you must answer
// Thought: you should always think about what to do
// Action: the action to take, should be one of [{tool_names}]
// Action Input: the input to the action
// Observation: the result of the action
// ... (this Thought/Action/Action Input/Observation can repeat N times)
// Thought: I now know the final answer
// Final Answer: the final answer to the original input question

// Question: {input}
// {agent_scratchpad}
// `);
//     const { createOpenAIFunctionsAgent } = require("langchain/agents");
//     const agent = await createOpenAIFunctionsAgent({
//     llm,
//     tools,
//     prompt
// });

//     const agentExecutor = new AgentExecutor({
//         agent,
//         tools,
//         verbose: true,
//         maxIterations: 10
//     });

//     const result = await agentExecutor.invoke({
//         input: "Process all overdue invoices step by step: first call read_invoices with empty string, then call calculate_stage with the result, then call generate_email with that result, then call save_logs with the final result."
//     });
//     return result;
// };


const runInvoiceAgent = async () => {
    const invoices = await readCSV();

    const enriched = invoices.map((invoice) => {
        const daysOverdue = calculateEscalationLevel(invoice.dueDate);
        const followUp = getFollowUpStage(daysOverdue);

        return {
            ...invoice,
            daysOverdue,
            stage: followUp.stage,
            tone: followUp.tone
        };
    });

    const results = [];

    for (const invoice of enriched) {
        if (invoice.daysOverdue <= 0) continue;

        if (invoice.stage === "ESCALATED") {
            continue;
        }

        const generatedEmail = await generateEmail(invoice);

        await saveLog({
            invoiceNumber: invoice.invoiceNumber,
            clientName: invoice.clientName,
            tone: invoice.tone,
            stage: invoice.stage,
            generatedEmail,
            timestamp: new Date(),
            status: "AGENT-GENERATED"
        });

        results.push({
            invoice,
            generatedEmail
        });
    }

    return {
        output: `Generated ${results.length} emails successfully`,
        results
    };
};

module.exports = { runInvoiceAgent };